all: add cmsc string print_rev fib

add: add.i
	ick add.i
cmsc: cmsc389.i
	ick cmsc389.i
string: string.i
	ick string.i
hello: hello_world.i
	ick hello_world.i
fib: fib.i
	ick fib.i
print_rev: print_rev.i
	ick print_rev.i
clean:
	rm add cmsc389 string fib print_rev
